/**
 * tal_adc.h — TAL ADC: pad-centric ADC ergonomics
 *
 * Wraps hal_adc using coregen-generated pad→channel mappings
 * (core_pad_adc_channel(), PAD_n_ADC_CH) and SYSCLK_HZ so that
 * application code can work entirely in pad numbers — the same
 * numbers used in config.json and on the tile silkscreen.
 *
 * Requires: core_pads.h, core_config.h (both generated by coregen).
 *
 * Typical usage:
 *
 *   #include "tal_adc.h"
 *
 *   hal_adc_t adc;
 *   tal_adc_init(&adc, HAL_ADC_RES_12BIT);
 *   tal_adc_add_pad(&adc, 5, HAL_ADC_SAMP_MED);
 *
 *   uint32_t mv = tal_adc_read_pad_mv(&adc, 5);
 *
 * Compare to the HAL equivalent:
 *
 *   hal_adc_init(&adc, ADC4, SYSCLK_HZ, HAL_ADC_RES_12BIT);  // need instance + clock
 *   hal_adc_add_channel(&adc, PAD_5_ADC_CH, HAL_ADC_SAMP_MED);  // need channel number
 *   uint32_t mv = hal_adc_read_mv(&adc, PAD_5_ADC_CH);
 *
 * DMA / continuous mode — also pad-centric:
 *   tal_adc_start_dma(&adc, buf, len, callback, ctx);
 *   uint16_t v = tal_adc_dma_read_pad(&adc, 5);  // index looked up automatically
 *   tal_adc_stop_dma(&adc);
 *
 * Oversampling applies globally — call hal_adc directly:
 *   hal_adc_set_oversample(&adc, HAL_ADC_OVERSAMPLE_64X);       // noise reduction
 *   hal_adc_set_oversample_ex(&adc, HAL_ADC_OVERSAMPLE_256X, 4); // → 16-bit effective
 */

#ifndef TAL_ADC_H
#define TAL_ADC_H

#include "hal_adc.h"
#include "core_pads.h"    /* core_pad_adc_channel(), PAD_n_ADC_CH */
#include "core_config.h"  /* SYSCLK_HZ */

/* ============================================================
 * Core ADC instance
 *
 * Each Core tile has a single primary ADC peripheral.
 * Resolved from the MCU family define injected by the Makefile.
 * ============================================================ */

#if defined(STM32WBA55xx)
  /** Core.ST.W5 — WBA55 has a single ADC (ADC4, on AHB4) */
  #define CORE_ADC_INSTANCE   ADC4
#else
  /** Core.ST.L0 / Core.ST.L4 / Core.ST.H5 — all use ADC1 */
  #define CORE_ADC_INSTANCE   ADC1
#endif

/* ============================================================
 * Init
 * ============================================================ */

/**
 * Initialise the ADC.
 *
 * Equivalent to hal_adc_init(adc, CORE_ADC_INSTANCE, SYSCLK_HZ, res).
 * No need to look up which ADC peripheral your Core uses or what
 * SYSCLK_HZ is — both are resolved from coregen output.
 *
 * @param adc  Uninitialised handle
 * @param res  Conversion resolution (HAL_ADC_RES_12BIT for most uses)
 */
static inline hal_status_t tal_adc_init(hal_adc_t *adc, hal_adc_res_t res)
{
    return hal_adc_init(adc, CORE_ADC_INSTANCE, SYSCLK_HZ, res);
}

/* ============================================================
 * Channel registration
 * ============================================================ */

/**
 * Add a pad as an ADC input.
 *
 * Looks up the ADC channel number for pad via the coregen-generated
 * core_pad_adc_channel() helper, then calls hal_adc_add_channel.
 *
 * Returns HAL_ERROR if pad has no ADC function (not assigned as analog
 * in config.json, or the pad does not support ADC on this Core).
 *
 * @param adc   Initialised handle
 * @param pad   Tile pad number (e.g. 5 for pad 5)
 * @param samp  Sampling time — see hal_adc_samp_t
 */
static inline hal_status_t tal_adc_add_pad(hal_adc_t *adc, uint8_t pad,
                                            hal_adc_samp_t samp)
{
    int ch = core_pad_adc_channel(pad);
    if (ch < 0) return HAL_ERROR;   /* pad not ADC-capable or not assigned */
    return hal_adc_add_channel(adc, (uint8_t)ch, samp);
}

/* ============================================================
 * Blocking reads
 * ============================================================ */

/**
 * Single-shot blocking read — returns raw ADC count.
 *
 * @param adc  Initialised handle
 * @param pad  Pad number (must have been added via tal_adc_add_pad)
 * @return     Raw ADC count (0–4095 at 12-bit); 0 if pad is invalid
 */
static inline uint16_t tal_adc_read_pad(hal_adc_t *adc, uint8_t pad)
{
    int ch = core_pad_adc_channel(pad);
    if (ch < 0) return 0;
    return hal_adc_read(adc, (uint8_t)ch);
}

/**
 * Single-shot blocking read — returns VREFINT-calibrated millivolts.
 *
 * Uses the VREFINT factory calibration to account for the actual VDDA
 * supply voltage, so the result is correct even when VDD ≠ 3.3 V.
 *
 * @param adc  Initialised handle
 * @param pad  Pad number (must have been added via tal_adc_add_pad)
 * @return     Voltage in millivolts; 0 if pad is invalid
 */
static inline uint32_t tal_adc_read_pad_mv(hal_adc_t *adc, uint8_t pad)
{
    int ch = core_pad_adc_channel(pad);
    if (ch < 0) return 0;
    return hal_adc_read_mv(adc, (uint8_t)ch);
}

/* ============================================================
 * Internal channels
 *
 * No pad lookup needed — these read the ADC's internal inputs.
 * Provided here for API completeness so code that uses TAL
 * can include only tal_adc.h.
 * ============================================================ */

/**
 * Read die temperature in tenths of °C.
 * Example: 253 = 25.3 °C.
 * Auto-adds the internal temperature channel on first call.
 */
static inline int32_t tal_adc_read_temp_decidegc(hal_adc_t *adc)
{
    return hal_adc_read_temp_decidegc(adc);
}

/**
 * Read actual VDD supply voltage in millivolts via VREFINT.
 * Useful for battery-level estimation and supply-compensated calculations.
 */
static inline uint32_t tal_adc_read_vdda_mv(hal_adc_t *adc)
{
    return hal_adc_read_vdda_mv(adc);
}

/* ============================================================
 * DMA / continuous mode
 *
 * tal_adc_start_dma / tal_adc_stop_dma are thin pass-throughs —
 * channel setup has already been done via tal_adc_add_pad so there
 * is nothing extra to resolve.
 *
 * tal_adc_dma_read_pad provides the pad-number abstraction:
 * it looks up which slot in the DMA buffer corresponds to the
 * requested pad, matching the order channels were registered.
 * ============================================================ */

/**
 * Start continuous ADC conversion with DMA circular buffer.
 *
 * Channels must already be registered via tal_adc_add_pad.
 * The buffer must be at least adc->n_channels entries long for
 * one complete scan; typically a multiple of n_channels so the
 * callback fires every N complete scans.
 *
 * @param adc       Initialised handle
 * @param buf       Destination buffer (uint16_t[], DMA-accessible)
 * @param len       Buffer length in samples
 * @param callback  Called on half-transfer and full-transfer; may be NULL
 * @param ctx       User context passed to callback; may be NULL
 */
static inline hal_status_t tal_adc_start_dma(hal_adc_t *adc, uint16_t *buf,
                                              uint16_t len, hal_callback_t callback,
                                              void *ctx)
{
    return hal_adc_start_dma(adc, buf, len, callback, ctx);
}

/**
 * Stop continuous DMA conversion and release the DMA channel.
 */
static inline void tal_adc_stop_dma(hal_adc_t *adc)
{
    hal_adc_stop_dma(adc);
}

/**
 * Read the most recent DMA conversion result for a pad.
 *
 * Finds the buffer slot that corresponds to pad by matching its ADC
 * channel number against the registered channel list (i.e. the order
 * tal_adc_add_pad was called).  Returns 0 if the pad was not registered
 * or DMA is not active.
 *
 * @param adc  Initialised handle with active DMA
 * @param pad  Pad number (must have been added via tal_adc_add_pad)
 * @return     Most recent raw ADC count for that pad
 */
static inline int tal_adc_dma_slot(hal_adc_t *adc, uint8_t pad);

static inline uint16_t tal_adc_dma_read_pad(hal_adc_t *adc, uint8_t pad)
{
    if (!adc->dma_buf) return 0;
    int slot = tal_adc_dma_slot(adc, pad);
    if (slot < 0 || (uint16_t)slot >= adc->dma_len) return 0;
    return adc->dma_buf[slot];
}

/**
 * Buffer slot a pad's sample lands in within one DMA scan.
 *
 * This is NOT always the order pads were registered in:
 *
 *   L0 / WBA(ADC4)  CHSELR is a bitmask, and with SCANDIR = 0 the ADC
 *                   converts the selected channels in ascending
 *                   CHANNEL-NUMBER order, whatever order they were added
 *                   in. The slot is the channel's rank among the
 *                   registered channels.
 *   L4 / H5         SQR1..SQR4 are built from the registration order, so
 *                   slot == registration index.
 *
 * When the buffer holds several scans for oversampling
 * (len = n_channels * N), average slots slot, slot + n_channels,
 * slot + 2*n_channels, ...
 *
 * @return slot index, or -1 if the pad is not a registered ADC input
 */
static inline int tal_adc_dma_slot(hal_adc_t *adc, uint8_t pad)
{
    int ch = core_pad_adc_channel(pad);
    if (ch < 0) return -1;

    int registered = 0;
    for (uint8_t i = 0; i < adc->n_channels; i++) {
        if (adc->channels[i].channel == (uint8_t)ch) { registered = 1; break; }
    }
    if (!registered) return -1;

#if defined(STM32L011xx) || defined(STM32WBA55xx)
    int slot = 0;
    for (uint8_t i = 0; i < adc->n_channels; i++) {
        if (adc->channels[i].channel < (uint8_t)ch) slot++;
    }
    return slot;
#else
    for (uint8_t i = 0; i < adc->n_channels; i++) {
        if (adc->channels[i].channel == (uint8_t)ch) return (int)i;
    }
    return -1;
#endif
}


/**
 * Most recent DMA result for a pad, in calibrated millivolts.
 * VDDA must have been primed before DMA started — see hal_adc_raw_to_mv.
 */
static inline uint32_t tal_adc_dma_read_pad_mv(hal_adc_t *adc, uint8_t pad)
{
    return hal_adc_raw_to_mv(adc, tal_adc_dma_read_pad(adc, pad));
}

#endif /* TAL_ADC_H */
