#!/usr/bin/env python3
"""Embed a serial-update flasher binary in a C header the app links.

    python3 tools/gen_serial_update_blob.py --chip l4 --bin sdk/serial_update/build/flasher_l4.bin \
        --out sdk/hal/hal_serial_update_blob_l4.h
    python3 tools/gen_serial_update_blob.py --chip h5 --check --out sdk/hal/hal_serial_update_blob_h5.h

The header records a hash of the flasher's SOURCES, not of the binary, so
`--check` catches a forgotten regeneration without needing the ARM toolchain
(or the same compiler version) in CI. Normally driven by
`make -C sdk/serial_update` / `make -C sdk/serial_update check`.
"""

import argparse
import hashlib
import io
import os
import re
import sys

# Python entry points in tools/ force UTF-8 on their own streams (Windows).
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

COMMON = [
    "sdk/serial_update/su_core.c",
    "sdk/serial_update/su_core.h",
    "sdk/serial_update/su_protocol.h",
    "sdk/serial_update/Makefile",
    "sdk/ll/ll_flash.h",
    "sdk/ll/ll_rcc.h",
    "sdk/ll/ll_common.h",
]

CHIPS = {
    "l4": {"part": "STM32L422", "sources": ["sdk/serial_update/flasher_l4.c",
                                            "sdk/serial_update/flasher_l4.ld",
                                            "sdk/ll/ll_usb.h"]},
    "h5": {"part": "STM32H523", "sources": ["sdk/serial_update/flasher_h5.c",
                                            "sdk/serial_update/flasher_h5.ld",
                                            "sdk/ll/ll_usb_drd.h"]},
}


def source_hash(chip: str) -> str:
    h = hashlib.sha256()
    # The L4's file order is kept as it was, so its recorded hash only moves
    # when one of its inputs does.
    srcs = (CHIPS[chip]["sources"][:1] + COMMON[:3] + CHIPS[chip]["sources"][1:2] + COMMON[3:4]
            + CHIPS[chip]["sources"][2:] + COMMON[4:])
    for rel in srcs:
        with open(os.path.join(ROOT, rel), "rb") as f:
            data = f.read().replace(b"\r\n", b"\n")  # same hash on a CRLF checkout
        h.update(rel.encode() + b"\0" + data + b"\0")
    return h.hexdigest()[:16]


def render(chip: str, blob: bytes, src_hash: str) -> str:
    c, C = chip, chip.upper()
    rows = []
    for i in range(0, len(blob), 16):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) + ",")
    return (
        "/* GENERATED by tools/gen_serial_update_blob.py — do not edit.\n"
        " * Regenerate: make -C sdk/serial_update\n"
        " *\n"
        f" * Serial-update flasher for {CHIPS[chip]['part']}, linked to run at SU_FLASHER_BASE.\n"
        " * hal_usb_cdc.c copies it to SRAM and jumps to it (see su_protocol.h). */\n"
        "\n"
        f"#ifndef HAL_SERIAL_UPDATE_BLOB_{C}_H\n"
        f"#define HAL_SERIAL_UPDATE_BLOB_{C}_H\n"
        "\n"
        "#include <stdint.h>\n"
        "\n"
        f'#define SU_FLASHER_{C}_SRC_HASH "{src_hash}"\n'
        f"#define SU_FLASHER_{C}_LEN      {len(blob)}u\n"
        "\n"
        f"static const uint8_t su_flasher_{c}_bytes[SU_FLASHER_{C}_LEN] __attribute__((aligned(4))) = {{\n"
        + "\n".join(rows)
        + "\n};\n"
        "\n"
        f"#endif /* HAL_SERIAL_UPDATE_BLOB_{C}_H */\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--chip", choices=sorted(CHIPS), default="l4", help="which flasher")
    ap.add_argument("--bin", help="flasher binary (objcopy -O binary)")
    ap.add_argument("--out", required=True, help="header to write / check")
    ap.add_argument("--check", action="store_true", help="verify the header matches the sources")
    args = ap.parse_args()

    want = source_hash(args.chip)
    if args.check:
        try:
            with open(args.out, encoding="utf-8") as f:
                m = re.search(rf'SU_FLASHER_{args.chip.upper()}_SRC_HASH "([0-9a-f]+)"', f.read())
        except FileNotFoundError:
            m = None
        if not m or m.group(1) != want:
            print(f"{os.path.relpath(args.out, ROOT)} is stale — run: make -C sdk/serial_update",
                  file=sys.stderr)
            return 1
        print(f"{os.path.relpath(args.out, ROOT)} up to date ({want})")
        return 0

    if not args.bin:
        ap.error("--bin is required unless --check")
    with open(args.bin, "rb") as f:
        blob = f.read()
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(args.chip, blob, want))
    print(f"wrote {os.path.relpath(args.out, ROOT)} ({len(blob)} bytes, src {want})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
